### ISSUE TITLE
Get rid of HeightMaps

### ISSUE THREAD

**Issue by FridayItsFridayFriday** [QuasiStellar/Edgecase#42]
`HeightMap` can be replaced with `HexMap<Height>`.

`PerlinHeightMap` and `FlatHeightMap` can be replaced with `PerlinHeightMapGenerator` and `FlatHeightMapGenerator`.
They should just create and return a heightmap, instead of trying to be a heightmap.

**Comment by QuasiStellar** [comment]
Resolved in #49
